In [6]:
import pandas as pd
import numpy as np
import matplotlib as plt

data_main = pd.read_csv('sources/upload-weeklyshipcrossingsforsixmaritimepassagesofinterest.csv')
data_excel = pd.read_excel('sources/uktradeflowsofcontainerisedproductsthroughglobalmaritimepassages20202024.xlsx', sheet_name='1.Monthly Volumes All (Imports)')

In [7]:
data_main.head()

                Passage Week of entry  Number of crossings
0  Bab-Al Mandab Strait    03/01/2022                394.0
1  Bab-Al Mandab Strait    10/01/2022                391.0
2  Bab-Al Mandab Strait    17/01/2022                386.0
3  Bab-Al Mandab Strait    24/01/2022                394.0
4  Bab-Al Mandab Strait    31/01/2022                415.0

In [8]:
data_excel.head()

         Passage Direction      TEU  Year  Month
0  Taiwan Strait    import  13625.1  2020      1
1  Taiwan Strait    import   2710.4  2020      2
2  Taiwan Strait    import  11166.5  2020      3
3  Taiwan Strait    import     7766  2020      4
4  Taiwan Strait    import  11118.4  2020      5